name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Install Newman
        run: npm install --global newman@5

      - name: Lint with ruff
        run: ruff check .

      - name: Run pytest with coverage
        run: pytest

      - name: Start services
        run: docker compose up --build -d

      - name: Run Newman collection
        env:
          AUTH_BASE_URL: http://localhost:8001
          ACCOUNT_BASE_URL: http://localhost:8002
          TRANSACTION_BASE_URL: http://localhost:8003
        run: ./tests/postman/run_newman.sh

      - name: Stop services
        if: always()
        run: docker compose down

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
